Algoritmo "semnome"



Var
nome1, nome2 : caractere
idade1, idade2 : inteiro
media_idade : real


Inicio
escreval("Dados da Primeira Pessoa: ")
escreva("Nome: ")
leia(nome1)
escreva("Idade: ")
leia(idade1)

escreval("Dados da Segunda Pessoa: ")
escreva("Nome: ")
leia(nome2)
escreva("Idade: ")
leia(idade2)

media_idade <- (idade1 + idade2) / 2

escreva("A Idade média de" , nome1, "e ", nome2, "é de ", media_idade)



Fimalgoritmo